import {
    VerticalBox,
    HorizontalBox
} from "std-widgets.slint";

import {
    Log,
    Progress,
    Status,
    SingleSeparatorH,
    DoubleSeparatorV,
    FloatingButton
} from "./my-widgets/lib.slint";

import {
    EmptyPage,
    ProjectPage,
    CorePage,
    CopPkgPage,
    ValidatePage,
    SynthesisPage,
    FPGAPage
} from "./pages/lib.slint";

export component MainWindow inherits Window {
    property <int> stat;

    title: "Sasanqua IDE";
    preferred-width: 1280px;
    preferred-height: 800px;
    background: skyblue;

    // Progress
    Progress {
        y: 0;
        z: 0;
        height: 30px;
        background: root.background;

        stat: stat;
    }

    // Main View
    VerticalBox {
        z: 1;
        spacing: 0px;
        padding: 0px;

        // Page
        VerticalBox {
            height: 85%;
            spacing: 0px;
            padding: 8px;
            padding-top: 30px;

            Rectangle {
                EmptyPage     { enabled: true; }
                ProjectPage   { enabled: stat == 0; }
                CorePage      { enabled: stat == 1; }
                CopPkgPage    { enabled: stat == 2; }
                ValidatePage  { enabled: stat == 3; }
                SynthesisPage { enabled: stat == 4; }
                FPGAPage      { enabled: stat == 5; }
            }
        }

        DoubleSeparatorV {
            separator-color: black;
        }

        // Status View
        HorizontalBox {
            spacing: 0px;
            padding: 0px;

            // Log Viewer
            Log {
                width: 60%;
                logs: [];
            }

            SingleSeparatorH {
                separator-color: gray;
            }

            // Status Viewer
            Status {
                elems: [];
            }
        }
    }

    // Controller
    FloatingButton {
        x: 15px;
        y: ((root.height * 85%) - self.height) / 2;
        z: 2;

        enabled: stat != 0;
        size: 30px;
        text: "＜";

        clicked => { stat = max(0, stat - 1); }
    }

    FloatingButton {
        x: root.width - self.width - 15px;
        y: ((root.height * 85%) - self.height) / 2;
        z: 2;

        enabled: stat != 5;
        size: 30px;
        text: "＞";

        clicked => { stat = min(5, stat + 1); }
    }
}
