import {
    VerticalBox,
    HorizontalBox
} from "std-widgets.slint";

import {
    Log,
    Progress,
    SingleSeparatorH,
    DoubleSeparatorV,
    FloatingButton
} from "./my-widgets/lib.slint";

import {
    ProjectPage
} from "./pages/lib.slint";

export component MainWindow inherits Window {
    preferred-width: 1280px;
    preferred-height: 800px;
    background: skyblue;

    // Progress
    Progress {
        y: 0;
        z: 0;
        height: 30px;
        background: root.background;

        stat: 0;
    }

    // Main View
    VerticalBox {
        z: 1;
        spacing: 0px;
        padding: 0px;

        // Page
        VerticalBox {
            height: 85%;
            spacing: 0px;
            padding: 8px;
            padding-top: 30px;

            ProjectPage {}
        }

        DoubleSeparatorV {
            separator-color: black;
        }

        // Status View
        HorizontalBox {
            spacing: 0px;
            padding: 0px;

            // Log Viewer
            Log {
                width: 60%;
                text: "[INFO] 00:00:00 (user) > hello";
            }

            SingleSeparatorH {
                separator-color: gray;
            }

            // Log Viewer
            Log {
                text: "[INFO] 00:00:00 (user) > hello";
            }
        }
    }

    // Controller
    FloatingButton {
        x: 15px;
        y: ((root.height * 85%) - self.height) / 2;
        z: 2;

        enabled: true;
        size: 30px;
        text: "＜";
    }

    FloatingButton {
        x: root.width - self.width - 15px;
        y: ((root.height * 85%) - self.height) / 2;
        z: 2;

        enabled: true;
        size: 30px;
        text: "＞";
    }
}
