[workspace]
resolver = "2"
members = [
    # Launcher
    "launcher",
    "launcher_macros/macros",

    # UI
    "ui",

    # Event
    "event/event",
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
slint = "1.3"
slint-build = "1.3"
