import { Log } from "./Log.slint";
import { Progress } from "./Progress.slint";
import { Status } from "./Status.slint";
import { FloatingButton } from "./FloatingButton.slint";
import { SingleSeparatorV, SingleSeparatorH,
         DoubleSeparatorV, DoubleSeparatorH } from "./Separator.slint";
import { Space } from "./Space.slint";
import { TitledLineEdit } from "./TitledLineEdit.slint";
import { TitledSpinBox } from "./TitledSpinBox.slint";

export {
    Log,
    Progress,
    Status,
    FloatingButton,
    SingleSeparatorV,
    SingleSeparatorH,
    DoubleSeparatorV,
    DoubleSeparatorH,
    Space,
    TitledLineEdit,
    TitledSpinBox
}
