export component SingleSeparatorV inherits Rectangle {
    in property <color> separator-color;

    height: 1px;
    background: separator-color;
}

export component SingleSeparatorH inherits Rectangle {
    in property <color> separator-color;

    width: 1px;
    background: separator-color;
}

export component DoubleSeparatorV inherits Rectangle {
    in property <color> separator-color;

    height: 3px;
    background: white;
    border-width: 1px;
    border-color: separator-color;
}

export component DoubleSeparatorH inherits Rectangle {
    in property <color> separator-color;

    width: 3px;
    background: white;
    border-width: 1px;
    border-color: separator-color;
}
