import {
    HorizontalBox,
    SpinBox
} from "std-widgets.slint";

export component TitledSpinBox inherits HorizontalBox {
    in property <string> title;
    out property <int> count <=> spinbox.value;

    Text {
        text: title;
        font-size: 14px;
        vertical-alignment: center;
    }

    spinbox := SpinBox {
        width: 150px;
        value: 1;
        enabled: true;
    }
}
