[package]
name = "ide"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }

[workspace]
resolver = "2"
members = [
    "fpga_synth/fpga_synth",
    "gui/src-rs",
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
serde = "1.0.193"
