[package]
name = "worker_rlib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = "1.0"
rmp-serde = "1.1"
job = { package = "job", path = "../../job/job_job" }
