[package]
name = "pgen_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
vfs = { workspace = true }
ipgen = { package = "pgen_ipgen", path = "../pgen_ipgen" }
hwgen = { package = "pgen_hwgen", path = "../pgen_hwgen" }
