[package]
name = "pgen_ipgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
vfs = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
