[package]
name = "fpga_synth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
fpga_synth_job = { path = "../fpga_synth_job/job" }
fpga_synth_worker = { path= "../fpga_synth_worker/worker" }
