import {
    HorizontalBox,
    LineEdit
} from "std-widgets.slint";

export component TitledLineEdit inherits HorizontalBox {
    in property <string> title;
    in property <string> placeholder;
    out property <string> value <=> lineedit.text;

    Text {
        text: title;
        width: 80px;
        font-size: 14px;
        vertical-alignment: center;
    }

    lineedit := LineEdit {
        text: placeholder;
    }
}
