[package]
name = "copgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
vfs = "0.9"
tinytemplate = "1.1"
ipgen = { package = "ipgen", path = "../../tools/ipgen" }
