import { EmptyPage } from "./Empty.slint";
import { ProjectPage } from "./Project.slint";
import { CorePage } from "./Core.slint";
import { CopPkgPage } from "./CopPkg.slint";
import { ValidatePage } from "./Validate.slint";
import { SynthesisPage } from "./Synthesis.slint";
import { FPGAPage } from "./FPGA.slint";

export {
    EmptyPage,
    ProjectPage,
    CorePage,
    CopPkgPage,
    ValidatePage,
    SynthesisPage,
    FPGAPage
}
