import { VerticalBox } from "std-widgets.slint";

export component Page inherits Rectangle {
    in property <string> title;
    in property <bool> enabled;

    border-radius: 20px;
    border-width: 1px;
    background: white;
    visible: self.opacity != 0.0;
    opacity: enabled ? 1.0 : 0.0;

    animate opacity {
        duration: 100ms;
    }

    VerticalLayout {
        spacing: 8px;
        padding: 0px;
        alignment: start;

        VerticalLayout {
            padding: 16px;
            padding-top: 8px;
            padding-bottom: 8px;

            Text {
                text: title;
                font-weight: 700;
                font-size: 30px;
            }
        }

        VerticalLayout {
            x: 0;
            padding: 53px;
            padding-top: 8px;
            padding-bottom: 8px;

            @children
        }
    }
}
