import { VerticalBox , ScrollView} from "std-widgets.slint";

export component Page inherits Rectangle {
    in property <string> title;
    in property <bool> enabled;

    border-radius: 20px;
    border-width: 1px;

    background: white;
    visible: self.opacity != 0.0;
    opacity: enabled ? 1.0 : 0.0;

    drop-shadow-offset-x: 3px;
    drop-shadow-offset-y: 3px;
    drop-shadow-blur: 5px;
    drop-shadow-color: #568294;

    animate opacity {
        duration: 100ms;
    }

    VerticalLayout {
        width: 100%;
        height: parent.height;
        spacing: 8px;
        padding: 0px;
        alignment: start;

        VerticalLayout {
            padding: 16px;
            padding-top: 8px;
            padding-bottom: 8px;

            Text {
                text: title;
                font-weight: 700;
                font-size: 30px;
            }
        }

        ScrollView {
            height: parent.height - 52px;

            VerticalLayout {
                x: 0;
                padding: 53px;
                padding-top: 0px;
                padding-bottom: 0px;

                height: 100%;
                alignment: start;

                @children
            }
        }
    }
}
