import {
    HorizontalBox,
    ProgressIndicator,
    VerticalBox,
    SpinBox,
    Spinner,
    GroupBox,
    Button
} from "std-widgets.slint";

import { Page } from "./Page.slint";

import { Space } from "../my-widgets/lib.slint";

component SynthesisItem inherits HorizontalBox {
    in property <string> title;
    in property <bool> started;
    in property <bool> finished;

    Text {
        vertical-alignment: center;
        horizontal-alignment: left;

        font-weight: 500;
        font-size: 16px;

        text: title;
    }

    HorizontalBox {
        alignment: end;

        HorizontalBox {
            alignment: center;

            Text {
                vertical-alignment: center;

                font-weight: 700;
                font-size: 18px;

                text: started ? (finished ? "完了" : "実行中") : "待機";
            }

            Spinner {
                width: 16px;
                height: 16px;
                indeterminate: !finished;
            }
        }

        Text {
            vertical-alignment: center;

            font-weight: 500;
            font-size: 20px;

            text: "100%";
        }
    }
}

export component SynthesisPage inherits Page {
    title: "合成";

    GroupBox {
        title: "合成確認";

        VerticalBox {
            Text {
                font-size: 14px;
                text: "現在の設定で合成処理を開始しますか？";
            }

            Button {
                width: 20%;

                primary: true;
                text: "開始";
            }
        }
    }

    GroupBox {
        title: "合成状況";

        VerticalBox {
            spacing: -20px;
            alignment: center;

            SynthesisItem {
                title: "① プロセッサコア生成";
                started: true;
                finished: true;
            }

            SynthesisItem {
                title: "② コプロセッサパッケージ生成";
                started: true;
                finished: true;
            }

            SynthesisItem {
                title: "③ 論理合成";
                started: true;
                finished: false;
            }

            SynthesisItem {
                title: "④ 配置配線";
                started: false;
                finished: false;
            }

            SynthesisItem {
                title: "⑤ 合成結果ファイル出力";
                started: false;
                finished: false;
            }
        }
    }

    GroupBox {
        title: "合成結果";

        Text {
            font-size: 14px;
            text: "正常に合成処理が終了しました";
        }
    }
}
