[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
core = { path = "../core/core" }
gui_impl = { path = "./impl/src-rs" }
