[package]
name = "coregen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
vfs = "0.9"
ipgen = { package = "ipgen", path = "../../tools/ipgen" }
