[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
slint = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
